(************************************************
 * :: Identifier checkers
 ************************************************)

let is_lid id =
  assert (id <> "");
  match id.[0] with
  | 'a' .. 'z' | '_' -> true
  | _ -> false

let is_uid id =
  assert (id <> "");
  match id.[0] with
  | 'A' .. 'Z' -> true
  | _ -> false


(************************************************
 * :: Helper for ghost locations
 ************************************************)

let ghost file lnum =
  Camlp4.PreCast.Loc.of_tuple ("<generated by " ^ file ^ ".ml>", lnum, 0, 0, lnum, 0, 0, true)
