#include <valarray>
#include <vector>
#include <iostream>
#include <list>
#include <boost/lexical_cast.hpp>
#include <boost/foreach.hpp>
#include <boost/asio.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/intrusive_ptr.hpp>
#include <boost/fusion/mpl.hpp>
#include <boost/lambda/bind.hpp>
#include <boost/lambda/lambda.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>
#include <boost/archive/xml_iarchive.hpp>
#include <boost/archive/xml_oarchive.hpp>
#include <boost/type_traits.hpp>
#include <boost/signals2/signal.hpp>
#include <boost/format.hpp>

#include <QtGui/QTableWidget>
