(* cc_tokens.ml
 * do not edit; this file automatically generated by
 *   ./make-token-files -o cc_tokens c++1988.tok c++2011.tok gnu.tok
 *)

(* token flags *)
type token_flag =
  | TF_MULTISPELL     (* token has multiple spellings *)
  | TF_NONSEPARATOR   (* token is a nonseparator *)
  | TF_CPLUSPLUS      (* token is a keyword in C++, but an identifier in C *)

type token_type =
  | TOK_EOF
  | TOK_NAME
  | TOK_TYPE_NAME
  | TOK_VARIABLE_NAME
  | TOK_INT_LITERAL
  | TOK_FLOAT_LITERAL
  | TOK_STRING_LITERAL
  | TOK_CHAR_LITERAL
  | TOK_ASM
  | TOK_AUTO
  | TOK_BREAK
  | TOK_BOOL
  | TOK_CASE
  | TOK_CATCH
  | TOK_CDECL
  | TOK_CHAR
  | TOK_CLASS
  | TOK_CONST
  | TOK_CONST_CAST
  | TOK_CONTINUE
  | TOK_DEFAULT
  | TOK_DELETE
  | TOK_DO
  | TOK_DOUBLE
  | TOK_DYNAMIC_CAST
  | TOK_ELSE
  | TOK_ENUM
  | TOK_EXPLICIT
  | TOK_EXPORT
  | TOK_EXTERN
  | TOK_FALSE
  | TOK_FLOAT
  | TOK_FOR
  | TOK_FRIEND
  | TOK_GOTO
  | TOK_IF
  | TOK_INLINE
  | TOK_INT
  | TOK_LONG
  | TOK_MUTABLE
  | TOK_NAMESPACE
  | TOK_NEW
  | TOK_OPERATOR
  | TOK_PASCAL
  | TOK_PRIVATE
  | TOK_PROTECTED
  | TOK_PUBLIC
  | TOK_REGISTER
  | TOK_REINTERPRET_CAST
  | TOK_RETURN
  | TOK_SHORT
  | TOK_SIGNED
  | TOK_SIZEOF
  | TOK_STATIC
  | TOK_STATIC_CAST
  | TOK_STRUCT
  | TOK_SWITCH
  | TOK_TEMPLATE
  | TOK_THIS
  | TOK_THROW
  | TOK_TRUE
  | TOK_TRY
  | TOK_TYPEDEF
  | TOK_TYPEID
  | TOK_TYPENAME
  | TOK_UNION
  | TOK_UNSIGNED
  | TOK_USING
  | TOK_VIRTUAL
  | TOK_VOID
  | TOK_VOLATILE
  | TOK_WCHAR_T
  | TOK_WHILE
  | TOK_LPAREN
  | TOK_RPAREN
  | TOK_LBRACKET
  | TOK_RBRACKET
  | TOK_ARROW
  | TOK_COLONCOLON
  | TOK_DOT
  | TOK_BANG
  | TOK_TILDE
  | TOK_PLUS
  | TOK_MINUS
  | TOK_PLUSPLUS
  | TOK_MINUSMINUS
  | TOK_AND
  | TOK_STAR
  | TOK_DOTSTAR
  | TOK_ARROWSTAR
  | TOK_SLASH
  | TOK_PERCENT
  | TOK_LEFTSHIFT
  | TOK_RIGHTSHIFT
  | TOK_LESSTHAN
  | TOK_LESSEQ
  | TOK_GREATERTHAN
  | TOK_GREATEREQ
  | TOK_EQUALEQUAL
  | TOK_NOTEQUAL
  | TOK_XOR
  | TOK_OR
  | TOK_ANDAND
  | TOK_OROR
  | TOK_QUESTION
  | TOK_COLON
  | TOK_EQUAL
  | TOK_STAREQUAL
  | TOK_SLASHEQUAL
  | TOK_PERCENTEQUAL
  | TOK_PLUSEQUAL
  | TOK_MINUSEQUAL
  | TOK_ANDEQUAL
  | TOK_XOREQUAL
  | TOK_OREQUAL
  | TOK_LEFTSHIFTEQUAL
  | TOK_RIGHTSHIFTEQUAL
  | TOK_COMMA
  | TOK_ELLIPSIS
  | TOK_SEMICOLON
  | TOK_LBRACE
  | TOK_RBRACE
  | TOK_ANNOTATION
  | TOK_PREFER_REDUCE
  | TOK_PREFER_SHIFT
  | TOK_CONSTEXPR
  | TOK_NOEXCEPT
  | TOK_DECLTYPE
  | TOK_ALIGNOF
  | TOK_NULLPTR
  | TOK_STATIC_ASSERT
  | TOK_CHAR16_t
  | TOK_CHAR32_t
  | TOK___BUILTIN_CONSTANT_P
  | TOK___BUILTIN_VA_ARG
  | TOK___ALIGNOF__
  | TOK___OFFSETOF__
  | TOK___BUILTIN_OFFSETOF
  | TOK___ATTRIBUTE__
  | TOK___FUNCTION__
  | TOK___LABEL__
  | TOK___PRETTY_FUNCTION__
  | TOK___TYPEOF__
  | TOK___EXTENSION__
  | TOK_MIN_OP
  | TOK_MAX_OP
  | TOK_REAL
  | TOK_IMAG
  | TOK_RESTRICT
  | TOK_COMPLEX
  | TOK_IMAGINARY

let token_desc = function
  | TOK_EOF -> "<EOF>"
  | TOK_NAME -> "<name>"
  | TOK_TYPE_NAME -> "<type name>"
  | TOK_VARIABLE_NAME -> "<variable name>"
  | TOK_INT_LITERAL -> "<int literal>"
  | TOK_FLOAT_LITERAL -> "<float literal>"
  | TOK_STRING_LITERAL -> "<string literal>"
  | TOK_CHAR_LITERAL -> "<char literal>"
  | TOK_ASM -> "asm"
  | TOK_AUTO -> "auto"
  | TOK_BREAK -> "break"
  | TOK_BOOL -> "bool"
  | TOK_CASE -> "case"
  | TOK_CATCH -> "catch"
  | TOK_CDECL -> "cdecl"
  | TOK_CHAR -> "char"
  | TOK_CLASS -> "class"
  | TOK_CONST -> "const"
  | TOK_CONST_CAST -> "const_cast"
  | TOK_CONTINUE -> "continue"
  | TOK_DEFAULT -> "default"
  | TOK_DELETE -> "delete"
  | TOK_DO -> "do"
  | TOK_DOUBLE -> "double"
  | TOK_DYNAMIC_CAST -> "dynamic_cast"
  | TOK_ELSE -> "else"
  | TOK_ENUM -> "enum"
  | TOK_EXPLICIT -> "explicit"
  | TOK_EXPORT -> "export"
  | TOK_EXTERN -> "extern"
  | TOK_FALSE -> "false"
  | TOK_FLOAT -> "float"
  | TOK_FOR -> "for"
  | TOK_FRIEND -> "friend"
  | TOK_GOTO -> "goto"
  | TOK_IF -> "if"
  | TOK_INLINE -> "inline"
  | TOK_INT -> "int"
  | TOK_LONG -> "long"
  | TOK_MUTABLE -> "mutable"
  | TOK_NAMESPACE -> "namespace"
  | TOK_NEW -> "new"
  | TOK_OPERATOR -> "operator"
  | TOK_PASCAL -> "pascal"
  | TOK_PRIVATE -> "private"
  | TOK_PROTECTED -> "protected"
  | TOK_PUBLIC -> "public"
  | TOK_REGISTER -> "register"
  | TOK_REINTERPRET_CAST -> "reinterpret_cast"
  | TOK_RETURN -> "return"
  | TOK_SHORT -> "short"
  | TOK_SIGNED -> "signed"
  | TOK_SIZEOF -> "sizeof"
  | TOK_STATIC -> "static"
  | TOK_STATIC_CAST -> "static_cast"
  | TOK_STRUCT -> "struct"
  | TOK_SWITCH -> "switch"
  | TOK_TEMPLATE -> "template"
  | TOK_THIS -> "this"
  | TOK_THROW -> "throw"
  | TOK_TRUE -> "true"
  | TOK_TRY -> "try"
  | TOK_TYPEDEF -> "typedef"
  | TOK_TYPEID -> "typeid"
  | TOK_TYPENAME -> "typename"
  | TOK_UNION -> "union"
  | TOK_UNSIGNED -> "unsigned"
  | TOK_USING -> "using"
  | TOK_VIRTUAL -> "virtual"
  | TOK_VOID -> "void"
  | TOK_VOLATILE -> "volatile"
  | TOK_WCHAR_T -> "wchar_t"
  | TOK_WHILE -> "while"
  | TOK_LPAREN -> "("
  | TOK_RPAREN -> ")"
  | TOK_LBRACKET -> "["
  | TOK_RBRACKET -> "]"
  | TOK_ARROW -> "->"
  | TOK_COLONCOLON -> "::"
  | TOK_DOT -> "."
  | TOK_BANG -> "!"
  | TOK_TILDE -> "~"
  | TOK_PLUS -> "+"
  | TOK_MINUS -> "-"
  | TOK_PLUSPLUS -> "++"
  | TOK_MINUSMINUS -> "--"
  | TOK_AND -> "&"
  | TOK_STAR -> "*"
  | TOK_DOTSTAR -> ".*"
  | TOK_ARROWSTAR -> "->*"
  | TOK_SLASH -> "/"
  | TOK_PERCENT -> "%"
  | TOK_LEFTSHIFT -> "<<"
  | TOK_RIGHTSHIFT -> ">>"
  | TOK_LESSTHAN -> "<"
  | TOK_LESSEQ -> "<="
  | TOK_GREATERTHAN -> ">"
  | TOK_GREATEREQ -> ">="
  | TOK_EQUALEQUAL -> "=="
  | TOK_NOTEQUAL -> "!="
  | TOK_XOR -> "^"
  | TOK_OR -> "|"
  | TOK_ANDAND -> "&&"
  | TOK_OROR -> "||"
  | TOK_QUESTION -> "?"
  | TOK_COLON -> ":"
  | TOK_EQUAL -> "="
  | TOK_STAREQUAL -> "*="
  | TOK_SLASHEQUAL -> "/="
  | TOK_PERCENTEQUAL -> "%="
  | TOK_PLUSEQUAL -> "+="
  | TOK_MINUSEQUAL -> "-="
  | TOK_ANDEQUAL -> "&="
  | TOK_XOREQUAL -> "^="
  | TOK_OREQUAL -> "|="
  | TOK_LEFTSHIFTEQUAL -> "<<="
  | TOK_RIGHTSHIFTEQUAL -> ">>="
  | TOK_COMMA -> ","
  | TOK_ELLIPSIS -> "..."
  | TOK_SEMICOLON -> ";"
  | TOK_LBRACE -> "{"
  | TOK_RBRACE -> "}"
  | TOK_ANNOTATION -> "<annotation literal>"
  | TOK_PREFER_REDUCE -> "<prefer reduce>"
  | TOK_PREFER_SHIFT -> "<prefer shift>"
  | TOK_CONSTEXPR -> "constexpr"
  | TOK_NOEXCEPT -> "noexcept"
  | TOK_DECLTYPE -> "decltype"
  | TOK_ALIGNOF -> "alignof"
  | TOK_NULLPTR -> "nullptr"
  | TOK_STATIC_ASSERT -> "static_assert"
  | TOK_CHAR16_t -> "char16_t"
  | TOK_CHAR32_t -> "char32_t"
  | TOK___BUILTIN_CONSTANT_P -> "__builtin_constant_p"
  | TOK___BUILTIN_VA_ARG -> "__builtin_va_arg"
  | TOK___ALIGNOF__ -> "__alignof__"
  | TOK___OFFSETOF__ -> "__offsetof__"
  | TOK___BUILTIN_OFFSETOF -> "__builtin_offsetof"
  | TOK___ATTRIBUTE__ -> "__attribute__"
  | TOK___FUNCTION__ -> "__FUNCTION__"
  | TOK___LABEL__ -> "__label__"
  | TOK___PRETTY_FUNCTION__ -> "__PRETTY_FUNCTION__"
  | TOK___TYPEOF__ -> "__typeof__"
  | TOK___EXTENSION__ -> "__extension__"
  | TOK_MIN_OP -> "<?"
  | TOK_MAX_OP -> ">?"
  | TOK_REAL -> "__real__"
  | TOK_IMAG -> "__imag__"
  | TOK_RESTRICT -> "restrict"
  | TOK_COMPLEX -> "_Complex"
  | TOK_IMAGINARY -> "_Imaginary"

let token_index = function
  | TOK_EOF -> 0
  | TOK_NAME -> 1
  | TOK_TYPE_NAME -> 2
  | TOK_VARIABLE_NAME -> 3
  | TOK_INT_LITERAL -> 4
  | TOK_FLOAT_LITERAL -> 5
  | TOK_STRING_LITERAL -> 6
  | TOK_CHAR_LITERAL -> 7
  | TOK_ASM -> 8
  | TOK_AUTO -> 9
  | TOK_BREAK -> 10
  | TOK_BOOL -> 11
  | TOK_CASE -> 12
  | TOK_CATCH -> 13
  | TOK_CDECL -> 14
  | TOK_CHAR -> 15
  | TOK_CLASS -> 16
  | TOK_CONST -> 17
  | TOK_CONST_CAST -> 18
  | TOK_CONTINUE -> 19
  | TOK_DEFAULT -> 20
  | TOK_DELETE -> 21
  | TOK_DO -> 22
  | TOK_DOUBLE -> 23
  | TOK_DYNAMIC_CAST -> 24
  | TOK_ELSE -> 25
  | TOK_ENUM -> 26
  | TOK_EXPLICIT -> 27
  | TOK_EXPORT -> 28
  | TOK_EXTERN -> 29
  | TOK_FALSE -> 30
  | TOK_FLOAT -> 31
  | TOK_FOR -> 32
  | TOK_FRIEND -> 33
  | TOK_GOTO -> 34
  | TOK_IF -> 35
  | TOK_INLINE -> 36
  | TOK_INT -> 37
  | TOK_LONG -> 38
  | TOK_MUTABLE -> 39
  | TOK_NAMESPACE -> 40
  | TOK_NEW -> 41
  | TOK_OPERATOR -> 42
  | TOK_PASCAL -> 43
  | TOK_PRIVATE -> 44
  | TOK_PROTECTED -> 45
  | TOK_PUBLIC -> 46
  | TOK_REGISTER -> 47
  | TOK_REINTERPRET_CAST -> 48
  | TOK_RETURN -> 49
  | TOK_SHORT -> 50
  | TOK_SIGNED -> 51
  | TOK_SIZEOF -> 52
  | TOK_STATIC -> 53
  | TOK_STATIC_CAST -> 54
  | TOK_STRUCT -> 55
  | TOK_SWITCH -> 56
  | TOK_TEMPLATE -> 57
  | TOK_THIS -> 58
  | TOK_THROW -> 59
  | TOK_TRUE -> 60
  | TOK_TRY -> 61
  | TOK_TYPEDEF -> 62
  | TOK_TYPEID -> 63
  | TOK_TYPENAME -> 64
  | TOK_UNION -> 65
  | TOK_UNSIGNED -> 66
  | TOK_USING -> 67
  | TOK_VIRTUAL -> 68
  | TOK_VOID -> 69
  | TOK_VOLATILE -> 70
  | TOK_WCHAR_T -> 71
  | TOK_WHILE -> 72
  | TOK_LPAREN -> 73
  | TOK_RPAREN -> 74
  | TOK_LBRACKET -> 75
  | TOK_RBRACKET -> 76
  | TOK_ARROW -> 77
  | TOK_COLONCOLON -> 78
  | TOK_DOT -> 79
  | TOK_BANG -> 80
  | TOK_TILDE -> 81
  | TOK_PLUS -> 82
  | TOK_MINUS -> 83
  | TOK_PLUSPLUS -> 84
  | TOK_MINUSMINUS -> 85
  | TOK_AND -> 86
  | TOK_STAR -> 87
  | TOK_DOTSTAR -> 88
  | TOK_ARROWSTAR -> 89
  | TOK_SLASH -> 90
  | TOK_PERCENT -> 91
  | TOK_LEFTSHIFT -> 92
  | TOK_RIGHTSHIFT -> 93
  | TOK_LESSTHAN -> 94
  | TOK_LESSEQ -> 95
  | TOK_GREATERTHAN -> 96
  | TOK_GREATEREQ -> 97
  | TOK_EQUALEQUAL -> 98
  | TOK_NOTEQUAL -> 99
  | TOK_XOR -> 100
  | TOK_OR -> 101
  | TOK_ANDAND -> 102
  | TOK_OROR -> 103
  | TOK_QUESTION -> 104
  | TOK_COLON -> 105
  | TOK_EQUAL -> 106
  | TOK_STAREQUAL -> 107
  | TOK_SLASHEQUAL -> 108
  | TOK_PERCENTEQUAL -> 109
  | TOK_PLUSEQUAL -> 110
  | TOK_MINUSEQUAL -> 111
  | TOK_ANDEQUAL -> 112
  | TOK_XOREQUAL -> 113
  | TOK_OREQUAL -> 114
  | TOK_LEFTSHIFTEQUAL -> 115
  | TOK_RIGHTSHIFTEQUAL -> 116
  | TOK_COMMA -> 117
  | TOK_ELLIPSIS -> 118
  | TOK_SEMICOLON -> 119
  | TOK_LBRACE -> 120
  | TOK_RBRACE -> 121
  | TOK_ANNOTATION -> 122
  | TOK_PREFER_REDUCE -> 123
  | TOK_PREFER_SHIFT -> 124
  | TOK_CONSTEXPR -> 125
  | TOK_NOEXCEPT -> 126
  | TOK_DECLTYPE -> 127
  | TOK_ALIGNOF -> 128
  | TOK_NULLPTR -> 129
  | TOK_STATIC_ASSERT -> 130
  | TOK_CHAR16_t -> 131
  | TOK_CHAR32_t -> 132
  | TOK___BUILTIN_CONSTANT_P -> 133
  | TOK___BUILTIN_VA_ARG -> 134
  | TOK___ALIGNOF__ -> 135
  | TOK___OFFSETOF__ -> 136
  | TOK___BUILTIN_OFFSETOF -> 137
  | TOK___ATTRIBUTE__ -> 138
  | TOK___FUNCTION__ -> 139
  | TOK___LABEL__ -> 140
  | TOK___PRETTY_FUNCTION__ -> 141
  | TOK___TYPEOF__ -> 142
  | TOK___EXTENSION__ -> 143
  | TOK_MIN_OP -> 144
  | TOK_MAX_OP -> 145
  | TOK_REAL -> 146
  | TOK_IMAG -> 147
  | TOK_RESTRICT -> 148
  | TOK_COMPLEX -> 149
  | TOK_IMAGINARY -> 150
